### ISSUE TITLE
Unable to upload image succesfully after changing the "select backend" dropdown

### ISSUE THREAD

**Issue by cassiebreviu** [microsoft/onnxruntime-web-demo#1]
Repro steps:

1. nav to https://microsoft.github.io/onnxruntime-web-demo/#/squeezenet and keep the default selected "GPU" backend selected
2. click upload image and upload a image of a dog
3. the result is a classification as expected
4. Toggle the dropdown "CPU"
5. click "upload image" and upload the image of the dog again
6. the result is blank, no classification or visible error warning is observed

![image](https://user-images.githubusercontent.com/46505951/131049445-d1b47e27-e936-4733-b9b3-20f8fa90bc37.png)

**Comment by fs-eire** [comment]
thank you for the feedback! this issue is fixed in latest version.
